export const CLIENT_REPOSITORY = Symbol('CLIENT_REPOSITORY');
export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const EXCHANGE_RATE_REPOSITORY = Symbol('EXCHANGE_RATE_REPOSITORY');
export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
